parameters:
#    n_vieira_felipe_admin.example.class: NVieiraFelipe\AdminBundle\Example

services:
#    n_vieira_felipe_admin.example:
#        class: %n_vieira_felipe_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
